name: build-container

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - src/**
      - Dockerfile
      - version.txt

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Version
      id: version
      run: |
        IMAGE_VERSION=$(cat version.txt)
        echo "::set-output name=IMAGE_VERSION::${IMAGE_VERSION}"     

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: | 
          ${{ secrets.DOCKER_HUB_USERNAME }}/wschat:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/wschat:${{ steps.version.outputs.IMAGE_VERSION }}